### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by adamchainz** [ingresso-group/pyticketswitch#11]
At YPlan we're looking to move to Python 3 this year, `pyticketswitch` is one of our dependencies that doesn't yet support Python 3. We're happy to make PR's to move this forward, just wondering if there is any plan in place already? Thanks!

**Comment by rossgray** [comment]
We're definitely planning on adding Python 3 compatibility soon but haven't got round to working on it yet. You're more than welcome to make PRs for this in the meantime!

**Comment by nicwest** [comment]
hey guys, I'm going to close this one unless there is something more to be done?

**Comment by adamchainz** [comment]
I think we're happy with it, we've tested a lot on Python 3 and will be deploying in the next few weeks. If we find anything we'll make a PR.

**Comment by nicwest** [comment]
cool, shout at us if you find anything.
