### ISSUE TITLE
New API version(s)

### ISSUE THREAD

**Issue by nicwest** [ingresso-group/pyticketswitch#31]
We have a new API nearing completion which will introduce significant changes (json, removing (mostly) crypto blocks, terser and faster responses in places).

I want to take this opportunity to significantly restructure and rewrite pyticketswitch into a much leaner, more explicit, and reliable API wrapper. 

We have had a [v2-dev](https://github.com/ingresso-group/pyticketswitch/tree/v2-dev) branch floating around for a while where we pretty much deleted everything in master and started again. I'm planning to continue with this branch and eventually merge it into master. This will effectively deprecate the XML wrapper, it's objects, and workflow. 

I can appreciate that moving from the current wrapper to the new version might cause some headaches. To be clear the current version of the XML API will continue to work for the forseeable future and as such existing releases of this wrapper will continue to function. Additionally we will branch off of master with the current (at the time of v2 landing) HEAD for security and bug fixes for the XML wrapper.

Current ETA for the API completion is early December, and we aim to have v2 of pyticketswitch functional and tested  by early January.

Shout at us here if there is anything in particular you would like to see included. We are targeting primarily python 3 and aim to be compatible with python 2.7.

**Comment by adamchainz** [comment]
It's unclear whether we'll be able to move to v2 in the near term, thanks for offering security and bug fixes on v1 👍

**Comment by nicwest** [comment]
We have merged and released the v2-dev branch of pyticketswitch after about a month or so of testing internally. 

pypi: https://pypi.python.org/pypi/pyticketswitch/2.0.0
API documentation: https://ingresso-group.github.io/slate/
pyticketswitch documentation: https://ingresso-group.github.io/pyticketswitch/

At the time of this merge the version of the XML wrapper was [1.13.1](https://github.com/ingresso-group/pyticketswitch/releases/tag/1.13.1). A new branch has been created [stable/v1.x](https://github.com/ingresso-group/pyticketswitch/tree/stable/v1.x) that will handle on going fixes for the XML wrapper (these will hopefully be minimal).
