### ISSUE TITLE
Use requests instead of urllib2

### ISSUE THREAD

**Issue by graingert** [ingresso-group/pyticketswitch#5]
requests is more efficient and easier to use. It also supports validation of x509 certificates in Python 2.7.8

**Comment by nicwest** [comment]
@graingert It's certainly on the todo list!

**Comment by graingert** [comment]
Ideally I'd like to be able to pass in a requests session into Core, which default to one created internally

```python
pyticketswitch.Core(..., requests_session=my_custom_session)
```

**Comment by nicwest** [comment]
sure, seems sensible

**Comment by rossgray** [comment]
@graingert - I have added this to version 1.8.0. Can you check if this works for you? Please let me know if you have any comments.
