### ISSUE TITLE
Discount code should not be mandatory

### ISSUE THREAD

**Issue by rossgray** [ingresso-group/pyticketswitch#74]
It is possible for some events to not have a discount code, for example 6IE. Currently the `Discount` class expects a `code` to be passed into the constructor

**Comment by minusbat** [comment]
yes, at availabiloty stage there is no requirement for a discount code 
at all.

List discounts will always provide one though.

**Comment by joegrimeringresso** [comment]
See https://accesso.atlassian.net/browse/DSTBACK-408
