### ISSUE TITLE
Pyticketswitch support for external_management_url

### ISSUE THREAD

**Issue by ghost** [ingresso-group/pyticketswitch#97]
_As a Pyticketswitch user, I want the wrapper to support external_management_url so that my application can access the external booking management URL_

This is a prerequisite for https://github.com/ingresso-group/white-label/issues/1943.

**Acceptance Criteria**
1. This API property from the F13 API is available in the `Order` object
1. This update is described in the Pyticketswitch documentation

**Notes**
People who have worked on Pyticketswitch include Aaron, Konrad and Dan.

**Comment by joegrimeringresso** [comment]
https://accesso.atlassian.net/browse/DSTBACK-404
